### ISSUE TITLE
Addon CSS is overriding default Statamic V4 tailwind

### ISSUE THREAD

**Issue by Jaybuz** [daun/statamic-widget-collection-count#1]
Your `.w-full` is overriding the default responsive classes.

See my screenshot:
![image](https://github.com/daun/statamic-widget-collection-count/assets/140172/d0aa9f56-29ec-49f2-bf75-864e00bcbae7)

I would suggest removing the addon CSS and try to use the built-in Statamic Tailwind CSS instead. 

Thanks.

**Comment by daun** [comment]
If we don't bundle the styles used by the addon, there's a lot of tailwind classes that aren't available because they're not used inside of (and thus not compiled by) Statamic itself. So that's unfortunately not an option.

Can you think of a way to include the addon styles before the core files? Changing the order should intuitively solve this...

**Comment by Jaybuz** [comment]
A prefix would fix it:
https://tailwindcss.com/docs/configuration#prefix

**Comment by daun** [comment]
I've released [v1.1.1](https://github.com/daun/statamic-widget-collection-count/releases/tag/v1.1.1) with an updated tailwind configuration to not include `!important` statements.

Thanks for the pointer, and let me know if that fixes it for you.
